- name: Convertir string a lista de paquetes
  set_fact:
        paquetes: "{{ paquete.split(',') | map('trim') | list }}"

- name: Instalar paquetes indicados
  become: yes
  ansible.builtin.package:
    name: "{{ paquete }}"
    state: present
  register: resultado

- name: Mostrar resultado de la instalación
  debug:
    msg: "Paquetes instalados: {{ resultado.results | map(attribute='name') | list }}"